version: "3"

services:
  app:
    build:
      context: .
      target: dev
    command: npm run dev
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env.development
